// Copyright The Mumble Developers. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file at the root of the
// Mumble source tree or at <https://www.mumble.info/LICENSE>.

#ifndef CROSSAUDIO_CHANNEL_H
#define CROSSAUDIO_CHANNEL_H

#define CROSSAUDIO_CH_NUM (64)

// Keep values in sync with PipeWire's spa_audio_channel.
enum CrossAudio_Channel {
	CROSSAUDIO_CH_UNKNOWN = 0,
	CROSSAUDIO_CH_MONO    = 2,

	CROSSAUDIO_CH_FRONT_LEFT,
	CROSSAUDIO_CH_FRONT_RIGHT,
	CROSSAUDIO_CH_FRONT_CENTER,
	CROSSAUDIO_CH_LFE,
	CROSSAUDIO_CH_SIDE_LEFT,
	CROSSAUDIO_CH_SIDE_RIGHT,
	CROSSAUDIO_CH_FRONT_LEFT_CENTER,
	CROSSAUDIO_CH_FRONT_RIGHT_CENTER,
	CROSSAUDIO_CH_REAR_CENTER,
	CROSSAUDIO_CH_REAR_LEFT,
	CROSSAUDIO_CH_REAR_RIGHT,
	CROSSAUDIO_CH_TOP_CENTER,
	CROSSAUDIO_CH_TOP_FRONT_LEFT,
	CROSSAUDIO_CH_TOP_FRONT_CENTER,
	CROSSAUDIO_CH_TOP_FRONT_RIGHT,
	CROSSAUDIO_CH_TOP_REAR_LEFT,
	CROSSAUDIO_CH_TOP_REAR_CENTER,
	CROSSAUDIO_CH_TOP_REAR_RIGHT,
	CROSSAUDIO_CH_REAR_LEFT_CENTER,
	CROSSAUDIO_CH_REAR_RIGHT_CENTER,
	CROSSAUDIO_CH_FRONT_LEFT_WIDE,
	CROSSAUDIO_CH_FRONT_RIGHT_WIDE,
	CROSSAUDIO_CH_LFE2,
	CROSSAUDIO_CH_FRONT_LEFT_HIGH,
	CROSSAUDIO_CH_FRONT_CENTER_HIGH,
	CROSSAUDIO_CH_FRONT_RIGHT_HIGH,
	CROSSAUDIO_CH_TOP_FRONT_LEFT_CENTER,
	CROSSAUDIO_CH_TOP_FRONT_RIGHT_CENTER,
	CROSSAUDIO_CH_TOP_SIDE_LEFT,
	CROSSAUDIO_CH_TOP_SIDE_RIGHT,
	CROSSAUDIO_CH_LEFT_LFE,
	CROSSAUDIO_CH_RIGHT_LFE,
	CROSSAUDIO_CH_BOTTOM_CENTER,
	CROSSAUDIO_CH_BOTTOM_LEFT_CENTER,
	CROSSAUDIO_CH_BOTTOM_RIGHT_CENTER,
};

#endif
