name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'Ubuntu (Clang)'
            os: ubuntu-24.04
            cCompiler: 'clang'
            cppCompiler: 'clang++'
          - name: 'Ubuntu (GCC)'
            os: ubuntu-latest
            cCompiler: 'gcc'
            cppCompiler: 'g++'
          - name: 'Windows (Clang)'
            os: windows-latest
            cCompiler: 'clang-cl'
            cppCompiler: 'clang-cl'
          - name: 'Windows (MSVC)'
            os: windows-latest
            cCompiler: 'cl'
            cppCompiler: 'cl'

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 215a2535590f1f63788ac9bd2ed58ad15e6afdff

      - uses: lukka/run-cmake@v10
        with:
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER=${{matrix.cCompiler}}', '-DCMAKE_CXX_COMPILER=${{matrix.cppCompiler}}']"
          configurePreset: 'ninja-vcpkg'
          buildPreset: 'ninja-vcpkg'
          testPreset: 'ninja-vcpkg'
